#!/bin/bash
echo "++++++IP Grabbing from ifconfig+++++++"
echo "  ########  #######   ########  "
echo "     ##     ##    #      ##     "
echo "     ##     ## ###       ##     "
echo "     ##     ##    #      ##     "
echo "     ##     #######      ##     "
echo "-------------------------------------"



for ((x=1;x<99; x++))
do
if [[ $x%2 -ne 0 ]]
  then 
     echo "$x is odd"
fi
done
